// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.grpc.tp_grpc_spring.stubs;

public interface GetTotalSoldeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTotalSoldeRequest)
    com.google.protobuf.MessageOrBuilder {
}
