// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.grpc.tp_grpc_spring.stubs;

public interface SaveCompteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SaveCompteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return Whether the compte field is set.
   */
  boolean hasCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   * @return The compte.
   */
  com.grpc.tp_grpc_spring.stubs.CompteRequest getCompte();
  /**
   * <code>.CompteRequest compte = 1;</code>
   */
  com.grpc.tp_grpc_spring.stubs.CompteRequestOrBuilder getCompteOrBuilder();
}
