// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.grpc.tp_grpc_spring.stubs;

public interface GetAllComptesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllComptesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<com.grpc.tp_grpc_spring.stubs.Compte> 
      getComptesList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  com.grpc.tp_grpc_spring.stubs.Compte getComptes(int index);
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  int getComptesCount();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  java.util.List<? extends com.grpc.tp_grpc_spring.stubs.CompteOrBuilder> 
      getComptesOrBuilderList();
  /**
   * <code>repeated .Compte comptes = 1;</code>
   */
  com.grpc.tp_grpc_spring.stubs.CompteOrBuilder getComptesOrBuilder(
      int index);
}
