// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.grpc.tp_grpc_spring.stubs;

public interface GetComptesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetComptesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  com.grpc.tp_grpc_spring.stubs.TypeCompte getType();
}
