// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.grpc.tp_grpc_spring.stubs;

public interface GetCompteByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCompteByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * changed from string to int32
   * </pre>
   *
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
